### ISSUE TITLE
Why does this project exist?

### ISSUE THREAD

**Issue by ryboe** [lukeocodes/guys-bot#20]
Words have different meanings depending on context.

gendered: "The guys walked into a bar."
gender-neutral: "Hey guys, I walked into a bar."

I've said and heard the phrase "hey guys" perhaps thousands of times in my life. I've literally never encountered anyone being confused about the speaker's intent (maybe someone learning English?).

Given that "hey guys" has a clear gender-neutral meaning that's understood by _almost_ every English speaker, I have to ask respectfully: why does this project exist? What problem are you trying to solve? Where are the people who are being harmed by "hey guys"?

This project has the best intentions, but I think shaming people for saying something as banal, inoffensive, and neutral as "hey guys" is going to cause more harm than good. Even if the nag is only visible to the person who typed "hey guys", that can still provoke feelings of shame. Since this is likely being used at companies, people might fear that they'll face repercussions from their employers. Why put people through that when the gender-neutral intent is clear?

**Comment by lukeocodes** [comment]
Hey, I totally missed this!

It isn't shaming people. Read the related content, I guess.

**Comment by ryboe** [comment]
> ...the makeup of this Slack is very diverse. Some people feel excluded by the use of the term "guys".

This implies that the person 1) isn't conscious of diversity and 2) made people feel excluded. In other words, it's shaming them.

There's nothing wrong with saying "hey guys". This repo exists to shame people for doing nothing wrong.

**Comment by lukeocodes** [comment]
It doesn't shame anyone. Feel free to make a PR that would improve it :)

**Comment by ryboe** [comment]
lol

Me: * explains exactly how your bot shames people, quoting directly from your bot's messages *
You: No it doesn't.

> Feel free to make a PR that would improve it :)

The way to improve the repo is to delete the repo. This is a shamebot for policing your coworkers' speech, but your coworker's aren't doing anything wrong. You are.

**Comment by lukeocodes** [comment]
I'll never understand the anti-woke crusade. People can choose to use this, or choose not to. It's just code. So long :)
